version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:delegated
  server:
    image: node:12.7.0-alpine
    environment:
      NODE_ENV: "production"
    ports:
      - "4000:4000"
    volumes:
      - ./:/server:ro
    working_dir: /server
    command: yarn workspace @wuct/server start
    links:
      - db
    depends_on:
      - db
  client:
    image: nginx:1.17.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./packages/client/build/:/usr/share/nginx/html:ro
