export default [
  {
    id: '1',
    name: 'Ekaterina Tankova',
    email: 'ekaterina.tankova@devias.io',
    avatarUrl: '/images/avatars/avatar_3.png',
    createdAt: 1555016400000,
  },
  {
    id: '2',
    name: 'Cao Yu',
    email: 'cao.yu@devias.io',
    avatarUrl: '/images/avatars/avatar_4.png',
    createdAt: 1555016400000,
  },
  {
    id: '3',
    name: 'Alexa Richardson',
    email: 'alexa.richardson@devias.io',
    avatarUrl: '/images/avatars/avatar_2.png',
    createdAt: 1555016400000,
  },
  {
    id: '4',
    name: 'Anje Keizer',
    email: 'anje.keizer@devias.io',
    avatarUrl: '/images/avatars/avatar_5.png',
    createdAt: 1554930000000,
  },
  {
    id: '5',
    name: 'Clarke Gillebert',
    email: 'clarke.gillebert@devias.io',
    avatarUrl: '/images/avatars/avatar_6.png',
    createdAt: 1554757200000,
  },
  {
    id: '6',
    name: 'Adam Denisov',
    email: 'adam.denisov@devias.io',
    avatarUrl: '/images/avatars/avatar_1.png',
    createdAt: 1554670800000,
  },
  {
    id: '7',
    name: 'Ava Gregoraci',
    email: 'ava.gregoraci@devias.io',
    avatarUrl: '/images/avatars/avatar_7.png',
    createdAt: 1554325200000,
  },
  {
    id: '8',
    name: 'Emilee Simchenko',
    email: 'emilee.simchenko@devias.io',
    avatarUrl: '/images/avatars/avatar_8.png',
    createdAt: 1523048400000,
  },
  {
    id: '9',
    name: 'Kwak Seong-Min',
    email: 'kwak.seong.min@devias.io',
    avatarUrl: '/images/avatars/avatar_9.png',
    createdAt: 1522702800000,
  },
  {
    id: '10',
    name: 'Merrile Burgett',
    email: 'merrile.burgett@devias.io',
    avatarUrl: '/images/avatars/avatar_10.png',
    createdAt: 1522702800000,
  },
];
